### ISSUE TITLE
[BUG] cant send coin

### ISSUE THREAD

**Issue by robertbigk** [STATION-I/stai-blockchain#19]
**Describe the bug**

**To Reproduce**

2. Click on '....'   wallet take 6 stai send to destination address "Can't send more than 6000000000 in a single transaction"

**Expected behavior**
Send wallet works to transfer founds

**Screenshots**
![mstsc_HPj7dhfY52](https://user-images.githubusercontent.com/34956477/143252904-8f115c44-f2b6-4a50-b139-2f285cda6993.png)

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by WarutaShinken** [comment]
This is probably due to how the STAI in your wallet is broken up. There's a limit to how many UTXOs can be spent in Chia forks. Closing due to old age of issue and due to the fact it's a Chia problem.
