### ISSUE TITLE
[FEATURE REQUEST] maintain latest branch

### ISSUE THREAD

**Issue by MartijnGevaert** [STATION-I/stai-blockchain#25]
**NOT A BUG, but a request**

Stai can be installed using the same scripts as chia-blockchain if you were to provide a `latest` branch.
This would need to be maintained and updated with each release though.
Install instructions:
https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian

**Comment by WarutaShinken** [comment]
Done. This branch will be updated on every release, while `main` will include `.md` file/documentation updates and simple, bleeding edge fixes that should still be production ready.
