### ISSUE TITLE
[BUG] v2 db fails stai db validate

### ISSUE THREAD

**Issue by jfikar** [STATION-I/stai-blockchain#26]
Hi, I'm trying the new Stai 1.2.0 and I converted the v1 db to v2 db using `stai db upgrade`. The new chia v2 code has also a tool to verify the integrity of the v2 db, so I tried `stai db validate`. It fails with following error:
```
$ stai db validate
Unable to check permissions for /home/pi/stai-blockchain/mozilla-ca/cacert.pem: file /home/pi/stai-blockchain/mozilla-ca/cacert.pem does not exist
opening file for reading: /home/pi/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
peak hash: 43c806f78c17162eb3ad9d9f8a4e9af041932b90bcf0087ce19cf15e57286c57
peak height: 939007
traversing the full chain
0 orphaned blocks: 0      
FAILED: Blockchain has invalid genesis challenge b'0\x7f:\xb7D}\x15\x8dV\xb1H2?&n\xdaN\xd6=k\\nnZ\x90\x12\xaf`\x05\xf5@B', expected e6cee7cac7e6f0c93297804882fc64c326bb68da99d8b2d2690ace371c590b72
```

Probably it is harmless, I have seen that in other forks as well : https://github.com/Taco-Network/taco-blockchain/issues/11
Validate works for me flawlessly in chia and flax.

**Comment by WarutaShinken** [comment]
This will be fixed in the next update of Stai. Cheers.

**Comment by WarutaShinken** [comment]
Fixed
