### ISSUE TITLE
Current windows installer for 1.2.3 installs a Trojan Sabsik.FL!ml

### ISSUE THREAD

**Issue by OldButtKicking** [STATION-I/stai-blockchain#28]
![virus](https://user-images.githubusercontent.com/58090640/192120402-7171d270-8bf9-4595-987e-87e8da884d31.png)

**Describe the bug**
After upgrading to the 1.2.3 windows 11 throws attacked virus warning

**To Reproduce**
 Upgrade to latest version using windows installer StaiSetup-1.2.3.exe

**Expected behavior**
No virus is detected

**Screenshots**
Attached

**Desktop (please complete the following information):**

- OS: Windows 11, Alienware

**Comment by pnobrega80** [comment]
Mine, at windows 11 didn't accused anything

**Comment by WarutaShinken** [comment]
Can you guys test if 1.3.1 is flagged?

**Comment by WarutaShinken** [comment]
I will close this as `wontfix` as there's not much that can be done on our part. Chia doesn't get flagged as it's more popular than it's forks.
